title: "Cognitive Psychology Notes"
description: "Learning notes on cognitive science, language, and embodied cognition"
baseurl: "" # For user.github.io repo, leave this empty
url: "https://your-username.github.io"
theme: minima

markdown: kramdown
highlighter: rouge

permalink: pretty

# Navigation links
collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag